import { readFile, mkdir, rm, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../../',import.meta.url));
const {version}=JSON.parse(await readFile(path.join(root,'package.json'),'utf8'));
const output=path.join(root,'dist/packages');
await mkdir(output,{recursive:true});
const name=`nodelane-act-website-${version}.zip`;
const zip=path.join(output,name);
await rm(zip,{force:true});
const quote=value=>`'${value.replaceAll("'","''")}'`;
await promisify(execFile)('powershell.exe',['-NoProfile','-NonInteractive','-Command',`Add-Type -AssemblyName System.IO.Compression.FileSystem\n[System.IO.Compression.ZipFile]::CreateFromDirectory(${quote(path.join(root,'website/dist'))}, ${quote(zip)})`],{windowsHide:true});
const digest=createHash('sha256').update(await readFile(zip)).digest('hex');
const sumfile=path.join(output,'SHA256SUMS.txt');
const lines=(await readFile(sumfile,'utf8')).split('\n').filter(line=>line && !line.endsWith(`  ${name}`));
await writeFile(sumfile,[...lines,`${digest}  ${name}`].join('\n')+'\n');
console.log(`Packaged static website: ${name}`);
