import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const root = fileURLToPath(new URL("../", import.meta.url));
export async function generate() {
  const dir = path.join(root, "sites");
  const folders = (await readdir(dir, { withFileTypes: true })).filter(e => e.isDirectory()).sort((a, b) => a.name.localeCompare(b.name));
  const manifests = [];
  const ids = new Set(), hosts = new Set();
  for (const folder of folders) {
    const filename = path.join(dir, folder.name, "manifest.json");
    const m = JSON.parse(await readFile(filename, "utf8"));
    if (!/^[a-z][a-z0-9-]{0,63}$/.test(m.id) || ids.has(m.id)) throw new Error(`Invalid/duplicate adapter id in ${filename}`);
    ids.add(m.id);
    if (!m.name || !m.description || !Array.isArray(m.hosts) || !m.hosts.length) throw new Error(`Incomplete manifest ${filename}`);
    for (const host of m.hosts) {
      if (!/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/.test(host) || hosts.has(host)) throw new Error(`Invalid/overlapping host ${host}`);
      hosts.add(host);
    }
    for (const key of ["operationsExport", "executeExport"]) if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(m[key])) throw new Error(`Invalid export ${key}`);
    const entry = path.resolve(path.dirname(filename), m.entry);
    const relative = path.relative(root, entry);
    if (relative.startsWith("..") || path.isAbsolute(relative) || !entry.endsWith(".ts")) throw new Error(`Adapter entry must be a TypeScript file inside this project: ${m.id}`);
    manifests.push({ ...m, resolvedEntry: entry });
  }
  const generatedDir = path.join(root, "src/generated");
  await mkdir(generatedDir, { recursive: true });
  const lines = manifests.map(m => {
    let importPath = path.relative(generatedDir, m.resolvedEntry).replaceAll("\\", "/").replace(/\.ts$/, ".js");
    if (!importPath.startsWith(".")) importPath = `./${importPath}`;
    return `  { id: ${JSON.stringify(m.id)}, name: ${JSON.stringify(m.name)}, description: ${JSON.stringify(m.description)}, hosts: ${JSON.stringify(m.hosts)}, load: async () => { const module = await import(${JSON.stringify(importPath)}); return { operations: module.${m.operationsExport}, execute: module.${m.executeExport} }; } }`;
  });
  await writeFile(path.join(generatedDir, "registry.ts"), `// Generated by scripts/generate.mjs; add sites/*/manifest.json instead of editing this file.\nimport type { AdapterRegistration } from "../shared/contracts.js";\nexport const adapterRegistrations: AdapterRegistration[] = [\n${lines.join(",\n")}\n];\n`);
  return manifests;
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await generate();
